### ISSUE TITLE
Stop digging around in the trash

### ISSUE THREAD

**Issue by Vernal** [postmatic/elevated-comments#7]
Comments which have been thrown to the trash are still being elevated on the front end. Can we filter by approved?

**Comment by carlalexander** [comment]
Did a small change to check if the comment is approved before generating HTML for it. This means that the elevated comment should disappear if you trash/spam a comment.

That said, this brings up a larger issue. We should scan for a new comment when the status of a comment changes. I'm leaving this open because of that. This is a slightly larger change so I won't be able to tackle it right away.
